#!/usr/bin/env bash

# Log a message to the collector log file
log() {
  echo "[$(date)] $1" >> /tmp/appsignal-collector.log
}

# Create or use the collector config file
create_or_use_config() {
  local build_dir="${BUILD_DIR:-/app}"
  local config_file="${build_dir}/.appsignal/etc/appsignal-collector.conf"
  local api_key="${APPSIGNAL_PUSH_API_KEY:-test-key-123}"

  if [ -f "$config_file" ]; then
    log "Using existing config file at $config_file"
  else
    log "Creating default config file at $config_file"
    mkdir -p "$(dirname "$config_file")"
    cat << EOF > "$config_file"
# AppSignal collector configuration
# Generated by Heroku buildpack
push_api_key = "${api_key}"
EOF
  fi
}

# Start the collector if it's not already running
start_collector() {
  local build_dir="${BUILD_DIR:-/app}"
  local collector_bin="${build_dir}/.appsignal/bin/appsignal-collector"
  local config_file="${build_dir}/.appsignal/etc/appsignal-collector.conf"

  if ! pgrep -x "appsignal-collector" > /dev/null; then
    log "Starting appsignal-collector"
    nohup "$collector_bin" start --config "$config_file" >> /tmp/appsignal-collector.log 2>&1 &
    # Store the PID for potential management
    echo $! > /tmp/appsignal-collector.pid
  else
    log "appsignal-collector already running"
  fi
}

# Create the profile script that will start the collector
create_profile_script() {
  local build_dir="${BUILD_DIR:-/app}"
  local profile_script="${build_dir}/.profile.d/appsignal.sh"

  mkdir -p "$(dirname "$profile_script")"
  echo '#!/usr/bin/env bash' > "$profile_script"
  echo '' >> "$profile_script"
  echo '# Source the config library' >> "$profile_script"
  echo "source \"${build_dir}/.appsignal/lib/config.sh\"" >> "$profile_script"
  echo '' >> "$profile_script"
  echo '# Call create_or_use_config to ensure a config file is available' >> "$profile_script"
  echo 'create_or_use_config' >> "$profile_script"
  echo '' >> "$profile_script"
  echo '# Start the collector' >> "$profile_script"
  echo 'start_collector' >> "$profile_script"

  chmod +x "$profile_script"
}
